import axios from "axios";
// El archivo version-info.js se genera durante el build
import {
  FRONTEND_VERSION as VERSION_FROM_FILE,
  FRONTEND_VERSION_DATE as DATE_FROM_FILE,
} from "../version-info.js";

const API_URL = "/api/version";

/**
 * Get the backend version and date from the API.
 * @returns {Promise<{version: string, date: string}|null>} The backend version info or null if error
 */
export async function getBackendVersion() {
  try {
    const response = await axios.get(API_URL);
    return response.data;
  } catch (error) {
    console.error("Error fetching backend version:", error);
    return null;
  }
}

/**
 * Get the frontend version from the auto-generated version-info.js file.
 * This file is generated by running 'npm run version:extract' which reads
 * the latest version from CHANGELOG.md.
 *
 * To update the version, run: npm run version:extract
 *
 * @returns {string} The frontend version string (e.g., "v0.1.8")
 */
export function getFrontendVersion() {
  return VERSION_FROM_FILE || "v0.1.8";
}

/**
 * Get the frontend version date from the auto-generated version-info.js file.
 * @returns {string} The frontend version date (e.g., "2025-10-05")
 */
export function getFrontendVersionDate() {
  return DATE_FROM_FILE || "unknown";
}
