#!/usr/bin/env node

/**
 * Script to extract the latest version from CHANGELOG.md
 * and create a version.js file that can be imported by the frontend.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CHANGELOG_PATH = path.join(__dirname, "../CHANGELOG.md");
const VERSION_OUTPUT_PATH = path.join(__dirname, "../src/version-info.js");

function extractVersion() {
  try {
    const changelogContent = fs.readFileSync(CHANGELOG_PATH, "utf-8");

    // Buscar la primera versión más reciente (no Unreleased)
    // Patrón: ## [v0.1.8] - 2025-10-05
    const versionPattern = /^## \[(v\d+\.\d+\.\d+)\] - (\d{4}-\d{2}-\d{2})/m;
    const match = changelogContent.match(versionPattern);

    if (match) {
      const version = match[1];
      const date = match[2];
      const versionCode = `// Auto-generated file - do not edit manually
// This file is generated by scripts/extract-version.js
// Run 'npm run version:extract' to regenerate

export const FRONTEND_VERSION = "${version}";
export const FRONTEND_VERSION_DATE = "${date}";
`;

      fs.writeFileSync(VERSION_OUTPUT_PATH, versionCode, "utf-8");
      console.log(`✅ Version extracted: ${version} (${date})`);
      return version;
    } else {
      console.warn("⚠️  No version found in CHANGELOG.md, using default");
      const defaultVersion = `export const FRONTEND_VERSION = "v0.0.0";
export const FRONTEND_VERSION_DATE = "unknown";`;
      fs.writeFileSync(VERSION_OUTPUT_PATH, defaultVersion, "utf-8");
      return "v0.0.0";
    }
  } catch (error) {
    console.error("❌ Error extracting version:", error);
    // Create a fallback file
    const fallbackVersion = `export const FRONTEND_VERSION = "v0.0.0";
export const FRONTEND_VERSION_DATE = "unknown";`;
    fs.writeFileSync(VERSION_OUTPUT_PATH, fallbackVersion, "utf-8");
    return "v0.0.0";
  }
}

extractVersion();
