// Auto-generated file - do not edit manually
// This file is generated by scripts/extract-version.js
// Run 'npm run version:extract' to regenerate

export const FRONTEND_VERSION = "v0.1.8";
export const FRONTEND_VERSION_DATE = "2025-10-05";
