name: Check Changelog Release

on:
  pull_request:
    branches: [main]

jobs:
  changelog-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate CHANGELOG release
        run: |
          # Check that [Unreleased] section has no entries
          UNRELEASED=$(sed -n '/## \[Unreleased\]/,/^## /p' CHANGELOG.md | grep -E '^\s*[-*]')
          if [ -n "$UNRELEASED" ]; then
            echo "❌ The [Unreleased] section still contains entries. Please release the changelog before merging."
            exit 1
          fi

          # Check that there is a released version section with a date
          VERSION_LINE=$(grep -E '^## \[v[0-9]+\.[0-9]+\.[0-9]+\] - [0-9]{4}-[0-9]{2}-[0-9]{2}' CHANGELOG.md | head -1)
          if [ -z "$VERSION_LINE" ]; then
            echo "❌ No released version found in CHANGELOG.md."
            exit 1
          fi

          echo "✅ Changelog release check passed."
