name: Check Changelog Release

on:
  pull_request:
    branches: [main]

jobs:
  changelog-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate CHANGELOG release
        run: |
          echo "=== DEBUGGING ==="
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          echo ""
          echo "First 20 lines of CHANGELOG.md:"
          head -20 CHANGELOG.md
          echo ""
          echo "=== [Unreleased] section content ==="
          sed -n '/## \[Unreleased\]/,/^## /p' CHANGELOG.md | cat -vet
          echo ""
          echo "=== Checking for entries ==="
          UNRELEASED=$(sed -n '/## \[Unreleased\]/,/^## /p' CHANGELOG.md | grep -E '^\s*[-*]' || true)
          echo "UNRELEASED content: '$UNRELEASED'"
          if [ -n "$UNRELEASED" ]; then
            echo "❌ The [Unreleased] section still contains entries. Please release the changelog before merging."
            exit 1
          fi

          # Check that there is a released version section with a date
          VERSION_LINE=$(grep -E '^## \[v[0-9]+\.[0-9]+\.[0-9]+\] - [0-9]{4}-[0-9]{2}-[0-9]{2}' CHANGELOG.md | head -1)
          echo "VERSION_LINE: '$VERSION_LINE'"
          if [ -z "$VERSION_LINE" ]; then
            echo "❌ No released version found in CHANGELOG.md."
            exit 1
          fi

          echo "✅ Changelog release check passed."
